server:
  servlet:
    context-path: /api
spring:
  application:
    name: kafka-consumer
  devtools:
    add-properties: false
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: group_id

topic:
  name:
    producer: topico.comando.teste

auto:
  create:
    topics:
      enable: true

springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    web: debug