server:
  port: 8888
  servlet:
    context-path: /api

spring:
  application:
    name: ms-auth
  devtools:
    add-properties: false
springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
#    csrf:
#      enabled: true

#rsa:
#  private-key: classpath:certs/private.pem
#  public-key: classpath:certs/public.pem

logging:
  level:
    web: debug

